project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: docked
    pinned: true
    collapse-level: 1
    contents:
      - index.ipynb
      - 00_core.ipynb
      - section: "reference examples"
        contents: examples/**

metadata-files: [nbdev.yml]
